apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: project-x-mgmt
spec:
  controller: {}
  ha:
    enabled: false
  rbac:
    defaultPolicy: ''
    policy: |
      g, project-x-admins, role:admin
      g, user1, role:admin
    scopes: '[groups]'
  redis: {}
  repo: {}
  server:
    route:
      enabled: true
  sso:
    dex:
      openShiftOAuth: true
    provider: dex
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - TaskRun
      - PipelineRun
